### ISSUE TITLE
Include all packages dependencies

### ISSUE THREAD

**Issue by bart-v** [EMODnet/EMODnetBiocheck#20]
Currently, you need to manually install some dependencies to make the installation work on R 4.x  i.e.
```
install.packages("devtools")
devtools::install_github("iobis/obistools")
devtools::install_github("EMODnet/skosxml")
install.packages("parsedate")
devtools::install_github("EMODnet/EMODnetBiocheck")
# Dependency for data.table::dcast in checkdataset fn
install.packages("reshape2")
# Dependency for reversetaxmatch
install.packages("rjson")
library(EMODnetBiocheck)
```

To be able to do
`loopcheckIPTdataset("<url>")`

So the packages above need to be added to the DESCRIPTION file, if not already the case

Best to rest with
`R --no-history`

**Comment by rubenpp7** [comment]
This is fixed now
