### ISSUE TITLE
Error: no applicable method for 'select' applied to an object of class "NULL"

### ISSUE THREAD

**Issue by rukayaj** [EMODnet/EMODnetBiocheck#27]
Hi folks, I'm looking at the rshiny app but it doesn't seem to work with my dwca - https://ipt.gbif.no/archive.do?r=radiolaria-bjorklund. Any ideas why ?

**Comment by rubenpp7** [comment]
Hi @rukayaj 

The issue happens because your scientificNameIDs are not LSIDs from WoRMS, I'll fix it in the coming days.
If you want to use the tool in the meantime you will have to remove those scientificNameIDs from the datasets (just temporarily, until I have ready the fix)

**Comment by rubenpp7** [comment]
Hi again @rukayaj 

issue fixed in https://github.com/EMODnet/EMODnetBiocheck/commit/00a7a478ff0230f61b63bd519df3378168bd1275 , now you can check your dataset

**Comment by rukayaj** [comment]
Thanks, that's sorted it!
