### ISSUE TITLE
$ operator is invalid for atomic vectors

### ISSUE THREAD

**Issue by meliezer** [EMODnet/EMODnetBiocheck#28]
Hi,
I get the above error for https://nodc.inogs.it/ipt/resource?r=dummy_dataset_please_ignore
using https://rshiny.lifewatch.be/BioCheck/

**Comment by rubenpp7** [comment]
Hi Menashe, 

I cannot reproduce your error, for me the dataset loads well, could it be that you have an empty space in the "Link to IPT resource" input box?

**Comment by meliezer** [comment]
Thank you @rubenpp7 ,
No, but I made a different error which the program could easily detect: I copied the link from the Manage list: I actually used https://nodc.inogs.it/ipt/manage/resource.do?r=dummy_dataset_please_ignore, and not the correct link I mentioned above...
You could verify if the URL includes 'resource?'. Anyway if '/manage/' is included it's an error.
I also assume you already trim possible trailing spaces :)

**Comment by rubenpp7** [comment]
Hi @meliezer 

I updated the url reading code, now it accounts for urls in edit mode (the ones with "/manage/") and it trims trailing spaces

**Comment by meliezer** [comment]
Perfect! Even better :) Thank you @rubenpp7

**Comment by meliezer** [comment]
Hi @rubenpp7 
The bug is back with a different dataset: https://nodc.ogs.it/ipt/resource?r=dummy_dataset_please_ignore

**Comment by rubenpp7** [comment]
Hi @meliezer 
the dataset you have shared seems to be private. Could you make it public and try again?

**Comment by meliezer** [comment]
I'm sorry, you are right! Closing this issue. Thank you!
