### ISSUE TITLE
Error: no applicable method for 'tbl_vars' applied to an object of class "NULL"

### ISSUE THREAD

**Issue by meliezer** [EMODnet/EMODnetBiocheck#29]
Dataset: https://nodc.inogs.it/ipt/resource?r=dummy_dataset_please_ignore

**Comment by rubenpp7** [comment]
Hi @meliezer 

I can't reproduce this issue, that URL works well for me in https://rshiny.lifewatch.be/BioCheck/
could you make sure that the URL that you put in the input box is the same that has been provided here?

**Comment by meliezer** [comment]
Hi @rubenpp7 
Yes. However I also fail to reproduce :)
Even https://nodc.inogs.it/ipt/manage/resource.do?r=dummy_dataset_please_ignore is OK now.
Thank you!
