### ISSUE TITLE
ERROR:  Biological value of 0 while occurrenceStatus is present   

### ISSUE THREAD

**Issue by MariaMakri** [EMODnet/EMODnetBiocheck#42]
In the stomach content database, there are measurements related to predator occurrences that might be 0 (such as the number of stomachs that are regurgitated

**Comment by rubenpp7** [comment]
I'll try to check why that is not picked up and come back to you

**Comment by rubenpp7** [comment]
BODC quantifications file added to check

**Comment by rubenpp7** [comment]
This should fix the issue https://github.com/EMODnet/EMODnetBiocheck/pull/44

I've decreased the error to a warning except for cases where the parameter is a known biological quantification. This means that you still will get it highlighted, but not as an error.

Changes also pushed to https://rshiny.lifewatch.be/BioCheck/
Please feel free to test it
