### ISSUE TITLE
BioCheck

### ISSUE THREAD

**Issue by melinalou** [EMODnet/EMODnetBiocheck#48]
Hi!We are trying to test our dataset with [Bio](https://rshiny.lifewatch.be/BioCheck/) using the url from the test mode of ipt.The BioCheck is not working, firstly has an error about invalid character $ for atomic vector and then it doesn't load at all. Is there something we could do?
You need to share with you the IPT resource or DwC-Archive that is failing but I am confused with this. https://ipt.vliz.be/upload/manage/resource.do?r=sahar this is the link from the ipt test that i putted in the BioCheck.
Thank you in advance!

**Comment by melinalou** [comment]
Indeed, thanks a lot!
One more question,we 've published the dataset and then check it with BioCheck but we faced this warning
![image](https://github.com/EMODnet/EMODnetBiocheck/assets/117156896/0d9d2700-3183-4ebd-bb91-1449dbc3321e)
about mesaurment type.We do not have specific type cause it is citizen science data. Is it ok to leave it empty or do you have to suggest anything?
Thank you!

**Comment by rubenpp7** [comment]
Hi @melinalou 

citizen scientist also use methodologies, how was that data collected? was it via images, visual observations, did they just picked shells in a beach or actually tow a hand net?

no matter if the data was collected via visual observations or by actual instruments such as nets or cameras, this could still be documented in the dataset. For example the sampling instrument name could be "cameras"
