### ISSUE TITLE
Add S13 to Biocheck tool BODC values

### ISSUE THREAD

**Issue by rubenpp7** [EMODnet/EMODnetBiocheck#63]
Add https://vocab.nerc.ac.uk/collection/S13/current/ to https://github.com/EMODnet/EMODnetBiocheck/blob/develop/files/BODC_tables_generator.py

**Comment by cyrilrader** [comment]
Done

**Comment by cyrilrader** [comment]
S13 has been added to the collection list of the python script: https://github.com/EMODnet/EMODnetBiocheck/blob/develop/files/BODC_tables_generator.py
